FROM python:3.12-slim

WORKDIR /app

# Копируем requirements и устанавливаем зависимости
COPY nutrition_backend/requirements.txt .
RUN pip install --default-timeout=300 --no-cache-dir -r requirements.txt

# Устанавливаем gunicorn и dateutil явно
RUN pip install --default-timeout=300 --no-cache-dir gunicorn python-dateutil

# Копируем весь код бэкенда
COPY nutrition_backend/ .

ENV PYTHONUNBUFFERED=1
ENV DJANGO_SETTINGS_MODULE=nutrition_backend.settings

EXPOSE 8000

CMD ["gunicorn", "nutrition_backend.wsgi:application", "--bind", "0.0.0.0:8000"]