# Generated by Django 4.2.30 on 2026-04-12 15:38

import api.managers
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='email address')),
                ('name', models.CharField(max_length=100, verbose_name='имя')),
                ('gender', models.CharField(choices=[('male', 'Мужской'), ('female', 'Женский')], default='male', max_length=10, verbose_name='пол')),
                ('age', models.PositiveIntegerField(default=25, verbose_name='возраст')),
                ('height', models.PositiveIntegerField(default=170, verbose_name='рост (см)')),
                ('weight', models.PositiveIntegerField(default=70, verbose_name='вес (кг)')),
                ('activity_level', models.CharField(choices=[('low', 'Низкий'), ('moderate', 'Умеренный'), ('high', 'Высокий'), ('very_high', 'Очень высокий')], default='moderate', max_length=20, verbose_name='уровень активности')),
                ('goal', models.CharField(choices=[('lose', 'Похудение'), ('maintain', 'Поддержание веса'), ('gain', 'Набор массы')], default='maintain', max_length=20, verbose_name='цель')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'пользователь',
                'verbose_name_plural': 'пользователи',
            },
            managers=[
                ('objects', api.managers.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('calories', models.FloatField(default=0, verbose_name='калории')),
                ('protein', models.FloatField(default=0, verbose_name='белки')),
                ('fat', models.FloatField(default=0, verbose_name='жиры')),
                ('carbs', models.FloatField(default=0, verbose_name='углеводы')),
                ('portion', models.FloatField(default=100, verbose_name='порция (г)')),
                ('date', models.DateField(verbose_name='дата')),
                ('meal_type', models.CharField(choices=[('breakfast', 'Завтрак'), ('lunch', 'Обед'), ('dinner', 'Ужин'), ('snack', 'Перекус')], default='breakfast', max_length=20, verbose_name='прием пищи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='дата создания')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_items', to=settings.AUTH_USER_MODEL, verbose_name='пользователь')),
            ],
            options={
                'verbose_name': 'запись о пище',
                'verbose_name_plural': 'записи о пище',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['user', 'date'], name='api_foodite_user_id_733f1f_idx')],
            },
        ),
    ]
